version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile-backend
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
